#!/bin/bash

more ./LICENSE

echo "Installing Perl packages..."
cpan -i use XML::Simple Time::HiRes File::Basename IO::Socket IO::Socket::Multicast IO::Select Data::Dumper

NAME=upnpd
PREFIX=/usr/local
BIN=$PREFIX/sbin
CONF=$PREFIX/etc/$NAME
RUN=PREFIX/var/run/$NAME
SPOOL=PREFIX/var/spool/$NAME

echo "Creating folders..."
mkdir -p $CONF
mkdir -p $CONF/devices.d
mkdir -p $CONF/services.d
mkdir -p $RUN
mkdir -p $SPOOL

echo "Copying files..."
cp ./etc/services.d/* $CONF/services.d/
cp ./etc/devices.d/* $CONF/devices.d/
cp -f ./bin/* $BIN/

echo "Do not forget to create OS specific start-up script!!!"
